apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: u4m6v5v4x-dotnet-basic
  janus-idp.io/tekton: u4m6v5v4x-dotnet-basic
  backstage.io/kubernetes-id: u4m6v5v4x-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u4m6v5v4x-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
